### ISSUE TITLE
Integration of the sails.js architecture as core backend service

### ISSUE THREAD

**Issue by wallynm** [wallynm/ttracker#6]
The first configuration of the app needs to be done in order to integrate the needed modules, @wmarra said that sails needs some specific rules to work properly and render all the static files correctly. This could be a nice place to we disscuss everything about it.

**Comment by wmarra** [comment]
Hi, I guess that we can use a more simple framework to develop our system, because sailsJS have many features on front-end layer and isn't necessary to us, because  @wallynm already started the to develop our front-end structure and doesn't need all those things in sailsJS. Other thing is, in sailsJS the connection with databases is started when the application set to run and this will generate more difficulty to connect in others services like cloud computers (Amazon for example). For these things I think to use a framework like [LoopBack](http://loopback.io/), [ExpressJS](http://expressjs.com/) and ORMs like [Mongoose](http://mongoosejs.com/) and [SequelizeJS](http://docs.sequelizejs.com/en/latest/). But we need to discuss more about it!

**Comment by wmarra** [comment]
In the last reunion we decided that we'll use Sails JS because it already have integrations with DynamoDB e RDS and we wont use multiple databases. I'll merge  front-end and back-end to continue development from our system.

**Comment by wmarra** [comment]
Hello guys,

I merged the develop branch with Sails JS.
After I'll explain the main files, I'm tired now... see ya!

**Comment by wallynm** [comment]
The sails structure will no longer be used
